/**
 * Space game typings
 * by EdJoPaTo
 * AGPL-3.0-or-later
 * https://github.com/EdJoPaTo/space-game-typings
 */

export type SiteEntity =
  | ({ type: "lifeless" } & SiteEntityLifeless)
  | ({ type: "facility" } & SiteEntityFacility)
  | ({ type: "npc" } & SiteEntityNpc)
  | ({ type: "player" } & SiteEntityPlayer);

/* Autogenerated after here */
